# Compila la version sin clases
enviarSinClases: enviarSinClases.cpp
	gcc -g enviarSinClases.pp -o enviarSinClases

recibirSinClases: recibirSinClases.cpp
	gcc -g recibirSinClases.cpp -o recibirSinClases
